#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CorpTraining.Droid.Resource", IsApplication=true)]

namespace CorpTraining.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06000d
			public const int audio_bg = 2131099661;
			
			// aapt resource value: 0x7f06000b
			public const int blue = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int colorAccent = 2131099653;
			
			// aapt resource value: 0x7f060003
			public const int colorPrimary = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int colorPrimaryDark = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int green = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int mediacontroller_bg = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int mediacontroller_bg_pressed = 2131099649;
			
			// aapt resource value: 0x7f06000c
			public const int sc_transparent_background = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int trans_white = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int trans_white2 = 2131099658;
			
			// aapt resource value: 0x7f060007
			public const int transgreen = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int transparent = 2131099650;
			
			// aapt resource value: 0x7f060008
			public const int transwhite = 2131099656;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_bottomtext_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_drawableleft_selector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_green_selector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_modulelist_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_red_selector = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_textmenu_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int checkbox_bg1 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int customer_progress = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int customer_progress_yellow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int login_button_bg_selector = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int login_button_bg_selector_red = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int mediacontroller_button = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int mediacontroller_pause = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int mediacontroller_play = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int progress_horizontal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int progress_horizontal_audio = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int progress_horizontal_score = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int scrubber_control_disabled_holo = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int scrubber_control_focused_holo = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int scrubber_control_normal_holo = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int scrubber_control_pressed_holo = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int scrubber_control_selector_holo = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int scrubber_primary_holo = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int scrubber_progress_horizontal_holo_dark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int scrubber_secondary_holo = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int scrubber_track_holo_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int selector_audio_btn_pause = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int selector_audio_btn_play = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int selector_btn_back = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int selector_btn_defaultscreen = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int selector_btn_exit = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int selector_btn_fullscreen = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int selector_btn_pause = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int selector_btn_play = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int selector_btn_voice = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int shape_bg = 2130837539;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090012
			public const int auto_save_password = 2131296274;
			
			// aapt resource value: 0x7f09002b
			public const int btn_back = 2131296299;
			
			// aapt resource value: 0x7f090010
			public const int btn_cancel = 2131296272;
			
			// aapt resource value: 0x7f090025
			public const int btn_continue = 2131296293;
			
			// aapt resource value: 0x7f090043
			public const int btn_exit = 2131296323;
			
			// aapt resource value: 0x7f09004b
			public const int btn_fullscreen = 2131296331;
			
			// aapt resource value: 0x7f09000f
			public const int btn_login = 2131296271;
			
			// aapt resource value: 0x7f090032
			public const int btn_next = 2131296306;
			
			// aapt resource value: 0x7f090035
			public const int btn_play = 2131296309;
			
			// aapt resource value: 0x7f090031
			public const int btn_pre = 2131296305;
			
			// aapt resource value: 0x7f09001c
			public const int btn_regback = 2131296284;
			
			// aapt resource value: 0x7f090042
			public const int btn_share = 2131296322;
			
			// aapt resource value: 0x7f090011
			public const int btn_signup = 2131296273;
			
			// aapt resource value: 0x7f090015
			public const int btn_start = 2131296277;
			
			// aapt resource value: 0x7f09002f
			public const int btn_submit = 2131296303;
			
			// aapt resource value: 0x7f090038
			public const int btn_voice = 2131296312;
			
			// aapt resource value: 0x7f090052
			public const int catalog = 2131296338;
			
			// aapt resource value: 0x7f090048
			public const int choicesRadioGrp = 2131296328;
			
			// aapt resource value: 0x7f090017
			public const int country_lvcountry = 2131296279;
			
			// aapt resource value: 0x7f09002a
			public const int details = 2131296298;
			
			// aapt resource value: 0x7f090000
			public const int dl_menu = 2131296256;
			
			// aapt resource value: 0x7f09004a
			public const int et_answer = 2131296330;
			
			// aapt resource value: 0x7f090022
			public const int et_email = 2131296290;
			
			// aapt resource value: 0x7f09001e
			public const int et_firstname = 2131296286;
			
			// aapt resource value: 0x7f090020
			public const int et_lastname = 2131296288;
			
			// aapt resource value: 0x7f090024
			public const int et_phonenumber = 2131296292;
			
			// aapt resource value: 0x7f090016
			public const int filter_edit = 2131296278;
			
			// aapt resource value: 0x7f090001
			public const int fl_content = 2131296257;
			
			// aapt resource value: 0x7f090030
			public const int fragmentContainer = 2131296304;
			
			// aapt resource value: 0x7f090003
			public const int ib_menu = 2131296259;
			
			// aapt resource value: 0x7f09000b
			public const int input = 2131296267;
			
			// aapt resource value: 0x7f09005d
			public const int iv_arrow = 2131296349;
			
			// aapt resource value: 0x7f09003c
			public const int iv_battery = 2131296316;
			
			// aapt resource value: 0x7f09004d
			public const int iv_icon = 2131296333;
			
			// aapt resource value: 0x7f090026
			public const int iv_scan = 2131296294;
			
			// aapt resource value: 0x7f090054
			public const int iv_titlepicture = 2131296340;
			
			// aapt resource value: 0x7f090009
			public const int left_menu = 2131296265;
			
			// aapt resource value: 0x7f09003e
			public const int ll_bottom_ctrl = 2131296318;
			
			// aapt resource value: 0x7f09004c
			public const int ll_comment = 2131296332;
			
			// aapt resource value: 0x7f090034
			public const int ll_content = 2131296308;
			
			// aapt resource value: 0x7f090049
			public const int ll_images = 2131296329;
			
			// aapt resource value: 0x7f09004e
			public const int ll_item = 2131296334;
			
			// aapt resource value: 0x7f090018
			public const int ll_load = 2131296280;
			
			// aapt resource value: 0x7f090033
			public const int ll_loading = 2131296307;
			
			// aapt resource value: 0x7f09000e
			public const int ll_logininfo = 2131296270;
			
			// aapt resource value: 0x7f09002c
			public const int ll_questions = 2131296300;
			
			// aapt resource value: 0x7f090013
			public const int ll_root = 2131296275;
			
			// aapt resource value: 0x7f090046
			public const int ll_text = 2131296326;
			
			// aapt resource value: 0x7f09003b
			public const int ll_top_ctrl = 2131296315;
			
			// aapt resource value: 0x7f09000c
			public const int login_accounts = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int login_password = 2131296269;
			
			// aapt resource value: 0x7f09000a
			public const int loginpage = 2131296266;
			
			// aapt resource value: 0x7f09001b
			public const int lv_list = 2131296283;
			
			// aapt resource value: 0x7f090029
			public const int lv_score = 2131296297;
			
			// aapt resource value: 0x7f09005b
			public const int mediacontroller_file_name = 2131296347;
			
			// aapt resource value: 0x7f090057
			public const int mediacontroller_play_pause = 2131296343;
			
			// aapt resource value: 0x7f09005a
			public const int mediacontroller_seekbar = 2131296346;
			
			// aapt resource value: 0x7f090058
			public const int mediacontroller_time_current = 2131296344;
			
			// aapt resource value: 0x7f090059
			public const int mediacontroller_time_total = 2131296345;
			
			// aapt resource value: 0x7f09002d
			public const int navigationTxt = 2131296301;
			
			// aapt resource value: 0x7f090028
			public const int pb_anti = 2131296296;
			
			// aapt resource value: 0x7f09005c
			public const int pb_progress = 2131296348;
			
			// aapt resource value: 0x7f090019
			public const int pb_pull_list_header = 2131296281;
			
			// aapt resource value: 0x7f090047
			public const int questionTxt = 2131296327;
			
			// aapt resource value: 0x7f090007
			public const int rb_account = 2131296263;
			
			// aapt resource value: 0x7f090006
			public const int rb_lessons = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int rb_settings = 2131296264;
			
			// aapt resource value: 0x7f090005
			public const int rg_functions = 2131296261;
			
			// aapt resource value: 0x7f090036
			public const int sb_audio = 2131296310;
			
			// aapt resource value: 0x7f090040
			public const int sb_video = 2131296320;
			
			// aapt resource value: 0x7f090039
			public const int sb_voice = 2131296313;
			
			// aapt resource value: 0x7f090053
			public const int title = 2131296339;
			
			// aapt resource value: 0x7f090050
			public const int tv_answer = 2131296336;
			
			// aapt resource value: 0x7f09003f
			public const int tv_current_position = 2131296319;
			
			// aapt resource value: 0x7f090056
			public const int tv_description = 2131296342;
			
			// aapt resource value: 0x7f090041
			public const int tv_duration = 2131296321;
			
			// aapt resource value: 0x7f090021
			public const int tv_email = 2131296289;
			
			// aapt resource value: 0x7f09001d
			public const int tv_firstname = 2131296285;
			
			// aapt resource value: 0x7f090027
			public const int tv_initiate = 2131296295;
			
			// aapt resource value: 0x7f09001f
			public const int tv_lastname = 2131296287;
			
			// aapt resource value: 0x7f090045
			public const int tv_loading = 2131296325;
			
			// aapt resource value: 0x7f090014
			public const int tv_maintitle = 2131296276;
			
			// aapt resource value: 0x7f09004f
			public const int tv_order = 2131296335;
			
			// aapt resource value: 0x7f090023
			public const int tv_phonenumber = 2131296291;
			
			// aapt resource value: 0x7f090037
			public const int tv_play_time = 2131296311;
			
			// aapt resource value: 0x7f09001a
			public const int tv_pull_list_header_title = 2131296282;
			
			// aapt resource value: 0x7f09005e
			public const int tv_refresh = 2131296350;
			
			// aapt resource value: 0x7f090051
			public const int tv_right = 2131296337;
			
			// aapt resource value: 0x7f090055
			public const int tv_size = 2131296341;
			
			// aapt resource value: 0x7f09003d
			public const int tv_system_time = 2131296317;
			
			// aapt resource value: 0x7f09005f
			public const int tv_time = 2131296351;
			
			// aapt resource value: 0x7f09002e
			public const int tv_timer = 2131296302;
			
			// aapt resource value: 0x7f090002
			public const int tv_title = 2131296258;
			
			// aapt resource value: 0x7f09003a
			public const int video_view = 2131296314;
			
			// aapt resource value: 0x7f090044
			public const int view_brightness = 2131296324;
			
			// aapt resource value: 0x7f090004
			public const int vp_content = 2131296260;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_home = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_login = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int activity_main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int activity_polices = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int activity_practices = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int activity_register = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int activity_result = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int activity_screens = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int activity_text = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int base_pager = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int fragment_audio = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int fragment_audiovideotext = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int fragment_basevideo = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int fragment_null = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int fragment_question = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int fragment_questionaudio = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int fragment_text = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int fragment_textaudio = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int fragment_textessayaudioimagefragment = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int fragment_textimageaudio = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int fragment_textquestionaudioimage = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int fragment_video = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int fragment_videotext = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int item_leftmenu = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int item_modulelist = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int item_resultlistview = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int item_users = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int item_videolist = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int mediacontroller = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int popup_authenticate = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int refresh_footer = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int refresh_header = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int viewpager_accountpager = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int viewpager_lessonspager = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int viewpager_settingspager = 2130968610;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int act_scanning_03 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int audio_seek_thumb = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int base_bg = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int bg_coop = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int bg_player_bottom_control = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int bg_player_bottom_seekbar = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int bg_player_status = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int bg_player_top_control = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int bottom_tab_bg = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int btn_audio_pause_normal = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int btn_audio_pause_pressed = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int btn_audio_play_normal = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int btn_audio_play_pressed = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int btn_default_screen_normal = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int btn_default_screen_pressed = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int btn_exit = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int btn_exit_pressed = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int btn_full_screen_normal = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int btn_full_screen_pressed = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int btn_pause_normal = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int btn_pause_pressed = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int btn_play_normal = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int btn_play_pressed = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int btn_voice_normal = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int btn_voice_pressed = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int checkbox_selected = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int checkbox_selected_press = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int checkbox_unselect = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int checkbox_unselect_press = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int common_listview_headview_red_arrow = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int coop_logo = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int default_bitmap = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int emotionstore_progresscancelbtn = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int function_greenbutton_normal = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int function_greenbutton_pressed = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int ic_battery_0 = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int ic_battery_10 = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int ic_battery_100 = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int ic_battery_20 = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int ic_battery_40 = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int ic_battery_60 = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int ic_battery_80 = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int ic_scanner_malware = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int Icon = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int icon_exit = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int icon_share = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int img_menu = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int landingscape = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int lessons = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int login_bg = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int login_button_nor = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int login_button_press = 2130903091;
			
			// aapt resource value: 0x7f030034
			public const int login_input = 2130903092;
			
			// aapt resource value: 0x7f030035
			public const int mailback = 2130903093;
			
			// aapt resource value: 0x7f030036
			public const int menu_arr_normal = 2130903094;
			
			// aapt resource value: 0x7f030037
			public const int menu_arr_select = 2130903095;
			
			// aapt resource value: 0x7f030038
			public const int menu_exit = 2130903096;
			
			// aapt resource value: 0x7f030039
			public const int next = 2130903097;
			
			// aapt resource value: 0x7f03003a
			public const int notepad = 2130903098;
			
			// aapt resource value: 0x7f03003b
			public const int personalaccount = 2130903099;
			
			// aapt resource value: 0x7f03003c
			public const int previous = 2130903100;
			
			// aapt resource value: 0x7f03003d
			public const int right_arrow = 2130903101;
			
			// aapt resource value: 0x7f03003e
			public const int search = 2130903102;
			
			// aapt resource value: 0x7f03003f
			public const int search_bar_icon_normal = 2130903103;
			
			// aapt resource value: 0x7f030040
			public const int seekbar_background = 2130903104;
			
			// aapt resource value: 0x7f030041
			public const int seekbar_thumb = 2130903105;
			
			// aapt resource value: 0x7f030042
			public const int selector_btn_voice = 2130903106;
			
			// aapt resource value: 0x7f030043
			public const int settings = 2130903107;
			
			// aapt resource value: 0x7f030044
			public const int title_bar = 2130903108;
			
			// aapt resource value: 0x7f030045
			public const int title_red_bg = 2130903109;
			
			// aapt resource value: 0x7f030046
			public const int top_back_left = 2130903110;
			
			// aapt resource value: 0x7f030047
			public const int top_back_leftpress = 2130903111;
			
			// aapt resource value: 0x7f030048
			public const int truck = 2130903112;
			
			// aapt resource value: 0x7f030049
			public const int video_default_icon = 2130903113;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int libarm = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070000
			public const int VideoView_error_button = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int VideoView_error_text_invalid_progressive_playback = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int VideoView_error_text_unknown = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int VideoView_error_title = 2131165187;
			
			// aapt resource value: 0x7f07000e
			public const int app_name = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int hello = 2131165197;
			
			// aapt resource value: 0x7f070004
			public const int mediacontroller_play_pause = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int permission_group_tools_description = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int permission_group_tools_label = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int permission_receive_messages_description = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int permission_receive_messages_label = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int permission_write_providers_description = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int permission_write_providers_label = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int vitamio_init_decoders = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int vitamio_library_app_name = 2131165196;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int MediaController_SeekBar = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int MediaController_Text = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int MyHorizontalProgressBar = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int NextStyle = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int PreviousStyle = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int RBstyle = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int TitleStyle = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int placeholder = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int subtitle = 2131230724;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
